paths:
  /api/products/:
    get:
      summary: Listar productos
      tags:
        - Products
      parameters:
        - name: page
          in: query
          description: Número de página de resultados
          required: false
          type: number
        - name: limit
          in: query
          description: Cantidad máxima de resultados
          required: false
          type: number
        - name: sort
          in: query
          description: Ordenamiento de resultados
          required: false
          type: string
          enum: [asc, desc]
        - name: query
          in: query
          description: Búsqueda por types de resultados
          required: false
          type: object
      responses:
        "200":
          description: Productos obtenidos correctamente
        "400":
          description: Error en la solicitud
        "404":
          description: Productos no encontrados
        "500":
          description: Error en el servidor
    post:
      summary: Crear un nuevo producto
      security:
        - bearerAuth: []
      tags:
        - Products
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/requestBodies/productBody"
      responses:
        "201":
          description: Producto creado correctamente
        "400":
          description: Error en la solicitud
        "401":
          description: Error de autenticación
        "403":
          description: Error de autorización
        "500":
          description: Error en el servidor
  /api/products/{pid}:
    get:
      summary: Obtener producto por ID
      tags:
        - Products
      parameters:
        - name: pid
          in: path
          required: true
          type: string
      responses:
        "200":
          description: Producto obtenido correctamente
        "400":
          description: Error en la solicitud
        "404":
          description: Producto no encontrado
        "500":
          description: Error en el servidor
    put:
      summary: Actualizar producto por ID
      security:
        - bearerAuth: []
      tags:
        - Products
      parameters:
        - name: pid
          in: path
          required: true
          type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/requestBodies/productBody"
      responses:
        "200":
          description: Producto actualizado correctamente
        "400":
          description: Error en la solicitud
        "401":
          description: Error de autenticación
        "403":
          description: Error de autorización
        "404":
          description: Producto no encontrado
        "500":
          description: Error en el servidor
    delete:
      summary: Eliminar producto por ID
      security:
        - bearerAuth: []
      tags:
        - Products
      parameters:
        - name: pid
          in: path
          required: true
          type: string
      responses:
        "200":
          description: Producto eliminado correctamente
        "400":
          description: Error en la solicitud
        "401":
          description: Error de autenticación
        "403":
          description: Error de autorización
        "404":
          description: Producto no encontrado
        "500":
          description: Error en el servidor
