paths:
  /api/products/:
    get:
      summary: Lista todos los productos
      tags:
        - Products
      parameters:
        - name: page
          in: query
          description: Número de página para la paginación
          required: false
          type: number
        - name: limit
          in: query
          description: Cantidad máxima de resultados por página
          required: false
          type: number
        - name: sort
          in: query
          description: Formato de ordenamiento para resultados
          required: false
          type: string
          enum: [asc, desc]
        - name: query
          in: query
          description: Formato de búsqueda por types
          required: false
          type: object
      responses:
        "200":
          description: Se obtienen los productos correctamente
        "400":
          description: Error en la solicitud
        "404":
          description: Productos no encontrados
        "500":
          description: Error en el servidor
    post:
      summary: Crea un nuevo producto
      security:
        - bearerAuth: []
      tags:
        - Products
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/requestBodies/productBody"
      responses:
        "201":
          description: Producto creado exitosamente
        "401":
          description: Error de autenticación
        "400":
          description: Error en la solicitud
        "500":
          description: Error en el servidor
  /api/products/{pid}:
    get:
      summary: Obtiene un producto por ID
      tags:
        - Products
      parameters:
        - name: pid
          in: path
          required: true
          type: string
      responses:
        "200":
          description: Producto encontrado exitosamente
        "404":
          description: Producto no encontrado
        "500":
          description: Error en el servidor
    put:
      summary: Actualiza un producto existente por ID
      security:
        - bearerAuth: []
      tags:
        - Products
      parameters:
        - name: pid
          in: path
          required: true
          type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/requestBodies/productBody"
      responses:
        "200":
          description: Producto actualizado exitosamente
        "404":
          description: Producto no encontrado
        "500":
          description: Error en el servidor
    delete:
      summary: Elimina un producto por ID
      security:
        - bearerAuth: []
      tags:
        - Products
      parameters:
        - name: pid
          in: path
          required: true
          type: string
      responses:
        "200":
          description: Producto eliminado exitosamente
        "404":
          description: Producto no encontrado
        "500":
          description: Error en el servidor
