paths:
  /api/roles/:
    get:
      summary: Listar roles
      tags:
        - Roles
      security:
        - BearerAuth: []
      responses:
        "200":
          description: Roles obtenidos correctamente
        "401":
          $ref: "#/components/responses/notAuthenticated"
        "403":
          $ref: "#/components/responses/notAuthorizated"
        "404":
          $ref: "#/components/responses/notFound"
        "500":
          $ref: "#/components/responses/serverError"
    post:
      summary: Crear un nuevo rol
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/requestBodies/rolBody"
      tags:
        - Roles
      responses:
        "201":
          description: Rol creado correctamente
        "400":
          $ref: "#/components/responses/requestError"
        "401":
          $ref: "#/components/responses/notAuthenticated"
        "403":
          $ref: "#/components/responses/notAuthorizated"
        "500":
          $ref: "#/components/responses/serverError"
  /api/roles/{rid}:
    get:
      summary: Obtener rol por ID
      tags:
        - Roles
      security:
        - BearerAuth: []
      parameters:
        - name: rid
          in: path
          required: true
          type: string
          description: ID del rol
      responses:
        "200":
          description: Rol obtenido correctamente
        "400":
          $ref: "#/components/responses/requestError"
        "401":
          $ref: "#/components/responses/notAuthenticated"
        "403":
          $ref: "#/components/responses/notAuthorizated"
        "404":
          $ref: "#/components/responses/notFound"
        "500":
          $ref: "#/components/responses/serverError"
    delete:
      summary: Eliminar rol por ID
      tags:
        - Roles
      security:
        - BearerAuth: []
      parameters:
        - name: rid
          in: path
          required: true
          type: string
          description: ID del rol
      responses:
        "200":
          description: Rol eliminado correctamente
        "400":
          $ref: "#/components/responses/requestError"
        "401":
          $ref: "#/components/responses/notAuthenticated"
        "403":
          $ref: "#/components/responses/notAuthorizated"
        "404":
          $ref: "#/components/responses/notFound"
        "500":
          $ref: "#/components/responses/serverError"
