paths:
  /api/roles/:
    get:
      summary: Listar roles
      tags:
        - Roles
      security:
        - BearerAuth: []
      responses:
        "200":
          description: Roles obtenidos correctamente
        "401":
          description: Error de autenticación
        "403":
          description: Error de autorización
        "404":
          description: Roles no encontrados
        "500":
          description: Error en el servidor
    post:
      summary: Crear un nuevo rol
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/requestBodies/rolBody"
      tags:
        - Roles
      responses:
        "201":
          description: Rol creado correctamente
        "400":
          description: Error en la solicitud
        "401":
          description: Error de autenticación
        "403":
          description: Error de autorización
        "500":
          description: Error en el servidor
  /api/roles/{rid}:
    get:
      summary: Obtener rol por ID
      tags:
        - Roles
      security:
        - BearerAuth: []
      parameters:
        - name: rid
          in: path
          required: true
          type: string
          description: ID del rol
      responses:
        "200":
          description: Rol obtenido correctamente
        "400":
          description: Error en la solicitud
        "401":
          description: Error de autenticación
        "403":
          description: Error de autorización
        "404":
          description: Rol no encontrado
        "500":
          description: Error en el servidor
    delete:
      summary: Eliminar rol por ID
      tags:
        - Roles
      security:
        - BearerAuth: []
      parameters:
        - name: rid
          in: path
          required: true
          type: string
          description: ID del rol
      responses:
        "200":
          description: Rol eliminado correctamente
        "400":
          description: Error en la solicitud
        "401":
          description: Error de autenticación
        "403":
          description: Error de autorización
        "404":
          description: Rol no encontrado
        "500":
          description: Error en el servidor
